JobSearch/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('', views.index, name='index')
]

jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('', views.index, name='index'),
    path('post', views.post, name='post'),
    path('find', views.find, name='find'),
    path('load', views.load, name='load'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('myposts', views.myposts, name='myposts'),
    path('<int:job_id>', views.delete, name='delete'),
    path('myjobs', views.myjobs, name='myjobs'),
]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User

class Job(models.Model):
    jobtitle = models.CharField(max_length=50)
    location = models.CharField(max_length=30)
    description = models.TextField(max_length=69420)
    about = models.TextField(max_length=69420)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="job_posts", default=1)

    def __str__(self):
        return self.jobtitle

users/models.py
from django.db import models

# Create your models here.

JobSearch/views.py
from django.http import HttpResponseRedirect
from django.urls.base import reverse

def index(request):
    return HttpResponseRedirect(reverse('jobs:index'))

jobs/views.py
import time
import json
from django.shortcuts import render
from django import forms
from django.urls.base import reverse
from jobs.models import Job
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.http import JsonResponse
from django.core import serializers

# Form for posting new job posts
class NewJobPost(forms.Form):
    jobtitle = forms.CharField(label = "Job Title: ", widget=forms.TextInput(attrs={'class' : 'form-control'}))
    location = forms.CharField(label = "Location: ", widget=forms.TextInput(attrs={'class' : 'form-control'}))
    description = forms.CharField(label = "Job Description: ", widget = forms.Textarea(attrs={'class' : 'form-control users_form-control'}))
    about = forms.CharField(label = "About the company: ", widget = forms.Textarea(attrs={'class' : 'form-control users_form-control'}))

def index(request):
    return render(request, 'jobs/index.html')

def find(request):
    return render(request, 'jobs/find.html')

# Used for loading searched job posts on 'find' page, infinite scroll
def load(request):
    if "j" in request.GET.keys():
        j = request.GET["j"]
        l = request.GET["l"]
        jobs = Job.objects.filter(jobtitle__icontains = j, location__icontains = l)
    else:
        jobs = Job.objects.all()

    start = int(request.GET.get("start") or 0)
    end = int (request.GET.get("end") or start + 9)

    qs = jobs[start - 1:end]
    qs_json = serializers.serialize('json', qs)

    if start != 1:
        time.sleep(1)

    return HttpResponse(qs_json, content_type = 'application/json')

def post(request):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'To post a job offer you need to login/register first.')
        return HttpResponseRedirect(reverse('users:login'))

    # If form is valid, save new job post
    if request.method == "POST":
        form = NewJobPost(request.POST)
        if form.is_valid():
            job = Job(jobtitle = form.cleaned_data["jobtitle"], 
                    location = form.cleaned_data["location"],
                    description = form.cleaned_data["description"],
                    about = form.cleaned_data["about"],
                    creator = request.user
                    )
            job.save()
        else:
            return render(request, 'jobs/post.html', {
                "form": form
    })
    return render(request, 'jobs/post.html', {
        "form": NewJobPost
    })

users/views.py
from django.forms.widgets import PasswordInput
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages
from jobs.models import Job
from django.core import serializers

class NewUser(forms.Form):
    username = forms.CharField(max_length=16, label="Username: ", help_text="Up to 16 characters", widget=forms.TextInput(attrs={'class' : 'form-control'}))
    first_name = forms.CharField(max_length=16, label="First Name: ", help_text="Up to 16 characters", widget=forms.TextInput(attrs={'class' : 'form-control'}))
    last_name = forms.CharField(max_length=16, label="Last Name: ", help_text="Up to 16 characters", widget=forms.TextInput(attrs={'class' : 'form-control'}))
    email = forms.EmailField(max_length=64, label="Email: ", required = False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    password = forms.CharField(max_length=16, label="Password: ", widget=PasswordInput(attrs={'class' : 'form-control'}))

# Returns the template with some user information
def index(request):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'You need to login first.')
        return HttpResponseRedirect(reverse('users:login'))

    return render(request, 'users/profile.html', {
        "user": request.user,
        "number_of_posts": len(request.user.job_posts.all())
    })

# If the user is authenticated, redirects to 'users/index.html', if not message is showed
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            messages.add_message(request, messages.ERROR, 'Invalid credentials')
    return render(request, 'users/login.html')

def register(request):
    if request.method == "POST":
        form = NewUser(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data["username"],
                first_name = form.cleaned_data["first_name"],
                last_name = form.cleaned_data["last_name"],
                email = form.cleaned_data["email"],
                password = form.cleaned_data["password"])
            user.save()
            messages.add_message(request, messages.SUCCESS, 'User created! Now go to the login page and login.')
        else:
            messages.add_message(request, messages.ERROR, 'Invalid form info')

    return render(request, 'users/register.html', {
        "form": NewUser
    })

def myposts(request):
    if request.user.is_authenticated:
        return render(request, 'users/myposts.html')
    return HttpResponseRedirect(reverse('users:login'))

def logout_view(request):
    logout(request)
    messages.add_message(request, messages.INFO, 'You have been logged out.')
    return render(request, 'users/login.html')

# Deletes the job post if the authenticated user is also the job post creator
def delete(request, job_id):
    if request.user.is_authenticated and request.user == Job.objects.get(pk=job_id).creator:
        model = Job.objects.get(pk=job_id)
        model.delete()
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:myposts'))
    return HttpResponseRedirect(reverse('users:login'))

# Returns JSON job posts that were created by authenticated user
def myjobs(request):
    return HttpResponse(serializers.serialize('json', request.user.job_posts.all()), content_type = 'application/json')
    

jobs/templates/jobs/find.html
{% extends 'jobs/layout.html' %}
{% load static %}

{% block body %}

<script src="{% static 'jobs/script.js' %}"></script>

<div class="searchbar">
  <form id="form" class="d-flex" action="{% url 'jobs:find' %}" method="get">
      <input class="form-control me-2" type="text" placeholder="Job Title, Keyword, Company..." name="j">
      <input class="form-control me-2" type="text" placeholder="Desired Location..." name="l">
      <input class="btn btn-outline-success" type="submit" value="Search">
  </form>
</div>


<div class="cards">
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
      </div>
      <div class="modal-body">
        <p id="about" style="white-space: pre-line;"></p>
        <p id="des" style="white-space: pre-line;"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

jobs/templates/jobs/index.html
{% extends 'jobs/layout.html' %}
{% load static %}

{% block body %}

<div class="background">
  <div class="searchbar">
    <form id="form" class="d-flex" action="{% url 'jobs:find' %}" method="get">
        <input class="form-control me-2" type="text" placeholder="Job Title, Keyword, Company..." name="j">
        <input class="form-control me-2" type="text" placeholder="Desired Location..." name="l">
        <input class="btn btn-outline-success" type="submit" value="Search">
    </form>
  </div>
</div>

{% endblock %}

jobs/templates/jobs/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>BestJob</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'jobs/style.css' %}">
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div style="display: inline-flex;">
          <a id="brand" class="navbar-brand" href="{% url 'jobs:index' %}">BestJob</a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item" style="padding-left: 30px; padding-top: 4px;">
                <a class="nav-link active" aria-current="page" href="{% url 'jobs:find' %}">Find jobs</a>
              </li>
              <li class="nav-item" style="padding-left: 30px; padding-top: 4px;">
                <a class="nav-link active" aria-current="page" href="{% url 'jobs:post' %}">Post jobs</a>
              </li>
            </ul>
          </div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" id="right-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, {{ request.user.username }}
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'users:index' %}">View profile</a>
                    <a class="dropdown-item" href="{% url 'users:myposts' %}">My job posts</a>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                  </div>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" style="color: rgb(45, 107, 170);">Sign in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}" style="color: rgb(45, 107, 170);">Sign up</a>
              </li>
              {% endif %}
            </ul>
            
          </div>
    </nav>
    {% block body %}
    {% endblock %} 
</body>
</html>

jobs/templates/jobs/post.html
{% extends 'jobs/layout.html' %}
{% load static %}

{% block body %}

<div class="user_form" style="min-width:60%">
    <div class="card w-75">
        <div class="card-body users_card-body">
            <h5 class="card-title users_card-title">Post a job</h5>
            <form action="{% url 'jobs:post' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <div class="center_btn">
                <input class="btn btn-primary" type="submit" value="Submit">
            </div>
            </form>
        </div>
    </div>    
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'jobs/layout.html' %}

{% block body %}

<div class="user_form">
    <div class="card w-75">
        <div class="card-body users_card-body">
          <h5 class="card-title users_card-title">Log in</h5>
          <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label class="form-label">Username:</label>
              <input type="text" class="form-control users_form-control" name="username">
            </div>
            <div class="mb-3">
              <label class="form-label">Password:</label>
              <input type="password" class="form-control users_form-control" name="password">
            </div>
            <input class="btn btn-primary users_btn" id="login_btn" type="submit" value="Log in">
          </form>
        </div>
    </div>
    {% if messages %}
    <div class="message">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

users/templates/users/myposts.html
{% extends 'jobs/layout.html' %}
{% load static %}

{% block body %}

<script src="{% static 'jobs/script.js' %}"></script>

<div class="message" style="margin-top: 30px;">

</div>

<div class="cards" style="margin-top: 30px;">
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
      </div>
      <div class="modal-body">
        <p id="des" style="white-space: pre-line;"></p>
        <p id="about" style="white-space: pre-line;"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="delete-modal">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a class="btn btn-danger" href="#" id="delete-button">Yes, delete it</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'jobs/layout.html' %}

{% block body %}

<div class="profile_info">
    <table class="table table-bordered">
        <tbody>
          <tr>
            <td>Username: </td>
            <td>{{ user.username }}</td>
          </tr>
          <tr>
            <td>First name: </td>
            <td>{{ user.first_name }}</td>
          </tr>
          <tr>
            <td>Last name: </td>
            <td>{{ user.last_name }}</td>
          </tr>
          <tr>
            <td>Email: </td>
            <td>{{ user.email }}</td>
          </tr>
          <tr>
            <td>Number of job posts: </td>
            <td>{{ number_of_posts }}</td>
          </tr>
        </tbody>
    </table>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'jobs/layout.html' %}

{% block body %}

<div class="user_form">
    <div class="card w-75">
        <div class="card-body users_card-body">
          <h5 class="card-title users_card-title">Register</h5>
            <form action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <div class="center_btn">
                <input class="btn btn-primary users_btn" type="submit" value="Submit">
            </div>
            </form>
        </div>
    </div>
    {% if messages %}
    <div class="message">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}